spring:
  profiles:
    active: local
      
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: 
    password: 

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
